# Generated by Django 5.1 on 2024-08-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("house_type", models.CharField(max_length=50)),
                ("available", models.BooleanField(default=True)),
                (
                    "rent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("main_image", models.ImageField(upload_to="houses/main/")),
            ],
        ),
        migrations.CreateModel(
            name="Landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="HouseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="houses/")),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="house_renting.house",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="house",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house_renting.landlord"
            ),
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.TextField(blank=True, null=True)),
                ("main_image", models.ImageField(upload_to="parcels/main/")),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_renting.landlord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParcelApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_contact_number", models.CharField(max_length=15)),
                ("message", models.TextField()),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_renting.parcel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParcelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="parcels/")),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="house_renting.parcel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_contact_number", models.CharField(max_length=15)),
                ("message", models.TextField()),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_renting.house",
                    ),
                ),
            ],
        ),
    ]
